chore: update tasks

diff --git a/taskfile b/taskfile
--- a/taskfile
+++ b/taskfile
@@ -392,6 +392,12 @@ function release {
         exit 1
     fi
 
+    if [ -n "$(git status --porcelain)" ]; then
+        echo "error: cannot pull with rebase: You have unstaged changes."
+        echo "error: please commit or stash them."
+        exit 1
+    fi
+
     # Fetch all changes from origin
     git fetch --all
     # Make sure we have the latest version file
